version: '3.6'
services:

  # POSTGRESQL IMAGE
  postgres:
    
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"

  # POSTGRESQL IMAGE LATEST
  postgreslatest:
    image: postgres:latest
    restart: always
    volumes:
    - db_data:/var/lib/postgresql2/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
    - "5433:5432"
  
  # PGADMIN IMAGE
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: eleuterio3d@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports: 
    - "8000:80"

  # MYSQL
  db:
      image: mysql:8.0.23
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      environment: 
        MYSQL_DATABASE: cuidapet_db
        MYSQL_ROOT_PASSWORD: cuidapet
      volumes: 
        - ../mysql_data:/var/lib/mysql

  # MONGODB
  mongodb:
    image: mongo:4.0.10
    restart: always
    ports:
    - "27017:27017"

  # GRAPHQL IMAGE
  graphql-engine:
    image: hasura/graphql-engine:v2.6.1
    ports:
    - "8001:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:12345@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:12345@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:


